-- InterestExplorer Database Schema Setup
-- Run this script in your Supabase SQL Editor to set up the necessary tables, relationships, security policies, and default interests.

-- 1. Interests Table
CREATE TABLE IF NOT EXISTS public.interests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    icon text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Profiles Table (linking auth users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. User Interests Mapping Table
CREATE TABLE IF NOT EXISTS public.user_interests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    interest_id bigint REFERENCES public.interests(id) ON DELETE CASCADE NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, interest_id)
);

-- 4. Bookmarks Table (Curiosity Journal)
CREATE TABLE IF NOT EXISTS public.bookmarks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    content text NOT NULL,
    type text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;

-- Enable SELECT access for authenticated users to view available interests
CREATE POLICY "Authenticated users can read interests" 
ON public.interests FOR SELECT 
TO authenticated
USING (true);

-- Profiles Policies
CREATE POLICY "Users can manage their own profile" 
ON public.profiles FOR ALL 
TO authenticated
USING (auth.uid() = id);

-- User Interests Policies
CREATE POLICY "Users can manage their own interests" 
ON public.user_interests FOR ALL 
TO authenticated
USING (auth.uid() = user_id);

-- Bookmarks Policies
CREATE POLICY "Users can manage their own bookmarks" 
ON public.bookmarks FOR ALL 
TO authenticated
USING (auth.uid() = user_id);

-- Seed Default Interests
INSERT INTO public.interests (name, icon) VALUES
('Coding', '💻'),
('Basketball', '🏀'),
('Startups', '🚀'),
('AI', '🤖'),
('Fitness', '💪'),
('Psychology', '🧠'),
('Music', '🎵'),
('Movies', '🎬'),
('Science', '🔬'),
('Business', '📈')
ON CONFLICT (name) DO NOTHING;
